### ISSUE TITLE
Setup test framework

### ISSUE THREAD

**Issue by benasher44** [benasher44/clornado#3]

**Comment by benasher44** [comment]
# Initial thoughts:

## test.html to run tests in the browser and run tests through local server:

### why this is good:
- have a dom
- all unit tests can be written in JavaScript
- runs a a real browser

### things that aren't so great about it:
- requires a browser
- can't easily automate on an integration/test server

**Comment by alexhaefner** [comment]
Yea as per our discussion, I agree.  js tests live in ~/src/js/tests? Python tests in ~/tests?  Are these tests against clornado, or tests against a user's application?

**Comment by benasher44** [comment]
We should use lib/js/tests for clornado (as needed), but if this is suppose to be an app template, then maybe we don't need tests, since this won't come with any routes?

Why python tests? Won't the JavaScript requests be testing our python stack?

**Comment by alexhaefner** [comment]
If js tests are being relied on to test the python stack, then those are more integration tests and not unit tests.  There should be standalone python tests that test python code paths, no?

**Comment by benasher44** [comment]
Yeah that makes sense. I think those python test should still just have routes though, so that we can just run the whole suite in test.html.

**Comment by alexhaefner** [comment]
That would be nice but it would limit the ability to accurately test python code

**Comment by alexhaefner** [comment]
i.e. if a request handler is throwing 500 errors, but you wanted to test that it threw 500 errors by calling a particular function/code path, you would have no way of verifying that.

**Comment by benasher44** [comment]
Can you be more specific?

**Comment by benasher44** [comment]
You can verify that a request return a 500 error, but I think it would be more helpful if we had python catch anything other than 200, and generated a report:
- error that would have happend (500, etc.)
- backtrace
- params and headers
- etc.

**Comment by alexhaefner** [comment]
Yes.  This is a contrived example.

Let's say you have a request handler that will throw a 500 error if the time of day is before noon, or a 400 error if the time of day is after noon.  Something like:

class UntestableByJavascript(RequestHandler):
def get(self):
  if(time_of_day_is_before_noon):
    raise tornado.web.HTTPError(500)
  else
    raise torando.web.HTTPError(400)

In this case, there is no way to test this using a javascript unit test.  We would be relying on running the test at the correct time to get the output you expect, but you would not be able to test the output from the other part of the if statement.  This is why you need python unit testing, so that you can mock out the time of day, and test both code paths, without any dependence on js running.

**Comment by benasher44** [comment]
My question is then: why can't you have the time of day be part of the request? I mean these are request handlers specifically for tests.

**Comment by alexhaefner** [comment]
How many things do you want to create rules for server side?  That is going to become a mess. 

Lets say I want to test how the site will respond with the db down.  So I send an argument as a part of the get request that will trigger python code to first pretend the db is down, then try and run the code path that was expected?  So what happens if I want to try mocking the database being down across a set of requests.

Okay, now what if I want to do a complex test for 4 different users, who are each considered to have different privileges across one request handler.  Then I have to log into user A, run the test with a huge set of extra get arguments, log out, and do the same for the other 4 users, because my browser cannot simulate 4 different users with different sessions at once.

Not to mention it will make debugging a request harder when a bunch of extra get arguments are appended to try and cover every single edge case I want to cover.  EG: GET '/send_angry_response?anger=5&message="BOO"&debug_db_out=True&debug_mock_start_time=12:35PM-EST&debug_mock_end_time=12:37PM-EST&debug_mock_get_cookie=<return cookie>'

Python unit testing is a must.  We can't put everything in the browser.  There would inevitably be many cases where the test would not be able to mock what it wanted easily, whereas just writing python unit tests would solve that problem.

We could potentially expose unit testing results through a get request, but it would inevitably be faster to run those tests in the command line.

**Comment by benasher44** [comment]
Ah ok. Understood. I just like the idea of having all of the tests in one place. Maybe we could just have one request handler to kick off the python unit tests? Then, we'll have all of reports in one place.
